export const Address = "0x83081bE6d9Df400850D3Bf5914b3D9766E230843";
export const ABI = [{ "inputs": [{ "internalType": "address", "name": "owner_", "type": "address" }], "stateMutability": "nonpayable", "type": "constructor" }, { "anonymous": false, "inputs": [{ "indexed": true, "internalType": "address", "name": "buyer", "type": "address" }, { "indexed": true, "internalType": "uint256", "name": "entryId", "type": "uint256" }, { "indexed": true, "internalType": "uint256", "name": "bidId", "type": "uint256" }, { "indexed": false, "internalType": "uint64", "name": "timestamp", "type": "uint64" }], "name": "Bid", "type": "event" }, { "anonymous": false, "inputs": [{ "indexed": false, "internalType": "uint256", "name": "bidId", "type": "uint256" }, { "indexed": false, "internalType": "uint256", "name": "entryId", "type": "uint256" }], "name": "BidSelected", "type": "event" }, { "anonymous": false, "inputs": [{ "indexed": false, "internalType": "uint256", "name": "bidId", "type": "uint256" }, { "indexed": false, "internalType": "uint256", "name": "entryId", "type": "uint256" }, { "indexed": false, "internalType": "uint256", "name": "value", "type": "uint256" }], "name": "BidWithdrawn", "type": "event" }, { "anonymous": false, "inputs": [{ "indexed": false, "internalType": "uint64", "name": "prevBiddingPeriod", "type": "uint64" }, { "indexed": false, "internalType": "uint64", "name": "newBiddingPeriod", "type": "uint64" }], "name": "BiddingPeriodUpdated", "type": "event" }, { "anonymous": false, "inputs": [{ "indexed": false, "internalType": "uint64", "name": "prevGracePeriod", "type": "uint64" }, { "indexed": false, "internalType": "uint64", "name": "newGracePeriod", "type": "uint64" }], "name": "GracePeriodUpdated", "type": "event" }, { "anonymous": false, "inputs": [{ "indexed": false, "internalType": "address", "name": "buyer", "type": "address" }, { "indexed": false, "internalType": "uint256", "name": "entryId", "type": "uint256" }, { "indexed": false, "internalType": "uint256", "name": "bidId", "type": "uint256" }, { "indexed": false, "internalType": "uint256", "name": "installmentNumber", "type": "uint256" }], "name": "InstallmentPaid", "type": "event" }, { "anonymous": false, "inputs": [{ "indexed": false, "internalType": "uint256", "name": "entryId", "type": "uint256" }, { "indexed": false, "internalType": "uint256", "name": "bidId", "type": "uint256" }, { "indexed": false, "internalType": "uint256", "name": "installmentPaid", "type": "uint256" }, { "indexed": false, "internalType": "uint256", "name": "value", "type": "uint256" }], "name": "Liquidated", "type": "event" }, { "anonymous": false, "inputs": [{ "indexed": true, "internalType": "address", "name": "user", "type": "address" }, { "indexed": true, "internalType": "address", "name": "newOwner", "type": "address" }], "name": "OwnerUpdated", "type": "event" }, { "anonymous": false, "inputs": [{ "indexed": false, "internalType": "uint256", "name": "bidId", "type": "uint256" }, { "indexed": false, "internalType": "uint256", "name": "entryId", "type": "uint256" }, { "indexed": false, "internalType": "uint256", "name": "value", "type": "uint256" }, { "indexed": false, "internalType": "uint256", "name": "paymentsClaimed", "type": "uint256" }], "name": "PaymentWithdrawn", "type": "event" }, { "anonymous": false, "inputs": [{ "indexed": true, "internalType": "address", "name": "seller", "type": "address" }, { "indexed": true, "internalType": "address", "name": "contractAddress", "type": "address" }, { "indexed": false, "internalType": "uint256", "name": "tokenId", "type": "uint256" }, { "indexed": true, "internalType": "uint256", "name": "entryId", "type": "uint256" }, { "indexed": false, "internalType": "uint64", "name": "timestamp", "type": "uint64" }], "name": "Sell", "type": "event" }, { "anonymous": false, "inputs": [{ "indexed": false, "internalType": "address", "name": "seller", "type": "address" }, { "indexed": false, "internalType": "uint256", "name": "entryId", "type": "uint256" }], "name": "SellWithdrawn", "type": "event" }, { "inputs": [], "name": "ONE_MONTH", "outputs": [{ "internalType": "uint64", "name": "", "type": "uint64" }], "stateMutability": "view", "type": "function" }, { "inputs": [{ "internalType": "uint256", "name": "entryId_", "type": "uint256" }, { "internalType": "uint256", "name": "bidPrice_", "type": "uint256" }, { "internalType": "enum ProjectY.InstallmentPlan", "name": "installment_", "type": "uint8" }], "name": "bid", "outputs": [{ "internalType": "uint256", "name": "", "type": "uint256" }], "stateMutability": "payable", "type": "function" }, { "inputs": [], "name": "biddingPeriod", "outputs": [{ "internalType": "uint64", "name": "", "type": "uint64" }], "stateMutability": "view", "type": "function" }, { "inputs": [{ "internalType": "uint256", "name": "entryId_", "type": "uint256" }], "name": "getAllBidsOnNFT", "outputs": [{ "components": [{ "internalType": "bool", "name": "isSelected", "type": "bool" }, { "internalType": "address", "name": "buyerAddress", "type": "address" }, { "internalType": "uint64", "name": "timestamp", "type": "uint64" }, { "internalType": "uint256", "name": "bidPrice", "type": "uint256" }, { "internalType": "uint256", "name": "entryId", "type": "uint256" }, { "internalType": "uint256", "name": "pricePaid", "type": "uint256" }, { "internalType": "enum ProjectY.InstallmentPlan", "name": "bidInstallment", "type": "uint8" }], "internalType": "struct ProjectY.BuyerInfo[]", "name": "allBidsOnNFT_", "type": "tuple[]" }, { "internalType": "uint256[]", "name": "bidIds_", "type": "uint256[]" }], "stateMutability": "view", "type": "function" }, { "inputs": [{ "internalType": "uint256", "name": "bidId_", "type": "uint256" }], "name": "getBuyerInfo", "outputs": [{ "components": [{ "internalType": "bool", "name": "isSelected", "type": "bool" }, { "internalType": "address", "name": "buyerAddress", "type": "address" }, { "internalType": "uint64", "name": "timestamp", "type": "uint64" }, { "internalType": "uint256", "name": "bidPrice", "type": "uint256" }, { "internalType": "uint256", "name": "entryId", "type": "uint256" }, { "internalType": "uint256", "name": "pricePaid", "type": "uint256" }, { "internalType": "enum ProjectY.InstallmentPlan", "name": "bidInstallment", "type": "uint8" }], "internalType": "struct ProjectY.BuyerInfo", "name": "", "type": "tuple" }], "stateMutability": "view", "type": "function" }, { "inputs": [{ "internalType": "uint256", "name": "bidId_", "type": "uint256" }], "name": "getDownPaymentAmount", "outputs": [{ "internalType": "uint256", "name": "", "type": "uint256" }], "stateMutability": "view", "type": "function" }, { "inputs": [], "name": "getHistoricTotalBidIds", "outputs": [{ "internalType": "uint256", "name": "", "type": "uint256" }], "stateMutability": "view", "type": "function" }, { "inputs": [], "name": "getHistoricTotalEntryIds", "outputs": [{ "internalType": "uint256", "name": "", "type": "uint256" }], "stateMutability": "view", "type": "function" }, { "inputs": [{ "internalType": "uint256", "name": "entryId_", "type": "uint256" }], "name": "getInstallmentAmountPerMonth", "outputs": [{ "internalType": "uint256", "name": "amount_", "type": "uint256" }], "stateMutability": "view", "type": "function" }, { "inputs": [{ "internalType": "uint256", "name": "bidId_", "type": "uint256" }, { "internalType": "uint64", "name": "installmentNumber_", "type": "uint64" }], "name": "getInstallmentMonthTimestamp", "outputs": [{ "internalType": "uint64", "name": "", "type": "uint64" }], "stateMutability": "view", "type": "function" }, { "inputs": [{ "internalType": "uint256", "name": "bidId_", "type": "uint256" }], "name": "getIsBidIdValid", "outputs": [{ "internalType": "bool", "name": "isValid_", "type": "bool" }], "stateMutability": "view", "type": "function" }, { "inputs": [{ "internalType": "uint256", "name": "entryId_", "type": "uint256" }], "name": "getIsEntryIdValid", "outputs": [{ "internalType": "bool", "name": "", "type": "bool" }], "stateMutability": "view", "type": "function" }, { "inputs": [], "name": "getNFTsOpenForSale", "outputs": [{ "components": [{ "internalType": "bool", "name": "onSale", "type": "bool" }, { "internalType": "address", "name": "sellerAddress", "type": "address" }, { "internalType": "address", "name": "contractAddress", "type": "address" }, { "internalType": "uint8", "name": "installmentsPaid", "type": "uint8" }, { "internalType": "uint8", "name": "paymentsClaimed", "type": "uint8" }, { "internalType": "uint64", "name": "timestamp", "type": "uint64" }, { "internalType": "uint256", "name": "tokenId", "type": "uint256" }, { "internalType": "uint256", "name": "sellingPrice", "type": "uint256" }, { "internalType": "uint256", "name": "totalBids", "type": "uint256" }, { "internalType": "uint256", "name": "selectedBidId", "type": "uint256" }, { "internalType": "enum ProjectY.InstallmentPlan", "name": "installment", "type": "uint8" }], "internalType": "struct ProjectY.SellerInfo[]", "name": "nftsOpenForSale_", "type": "tuple[]" }, { "internalType": "uint256[]", "name": "entryIds_", "type": "uint256[]" }], "stateMutability": "view", "type": "function" }, { "inputs": [{ "internalType": "uint256", "name": "entryId_", "type": "uint256" }], "name": "getSellerInfo", "outputs": [{ "components": [{ "internalType": "bool", "name": "onSale", "type": "bool" }, { "internalType": "address", "name": "sellerAddress", "type": "address" }, { "internalType": "address", "name": "contractAddress", "type": "address" }, { "internalType": "uint8", "name": "installmentsPaid", "type": "uint8" }, { "internalType": "uint8", "name": "paymentsClaimed", "type": "uint8" }, { "internalType": "uint64", "name": "timestamp", "type": "uint64" }, { "internalType": "uint256", "name": "tokenId", "type": "uint256" }, { "internalType": "uint256", "name": "sellingPrice", "type": "uint256" }, { "internalType": "uint256", "name": "totalBids", "type": "uint256" }, { "internalType": "uint256", "name": "selectedBidId", "type": "uint256" }, { "internalType": "enum ProjectY.InstallmentPlan", "name": "installment", "type": "uint8" }], "internalType": "struct ProjectY.SellerInfo", "name": "", "type": "tuple" }], "stateMutability": "view", "type": "function" }, { "inputs": [], "name": "getTotalBidIds", "outputs": [{ "internalType": "uint256", "name": "", "type": "uint256" }], "stateMutability": "view", "type": "function" }, { "inputs": [], "name": "getTotalEntryIds", "outputs": [{ "internalType": "uint256", "name": "", "type": "uint256" }], "stateMutability": "view", "type": "function" }, { "inputs": [{ "internalType": "uint256", "name": "bidId_", "type": "uint256" }], "name": "getTotalInstallments", "outputs": [{ "internalType": "uint8", "name": "", "type": "uint8" }], "stateMutability": "view", "type": "function" }, { "inputs": [{ "internalType": "address", "name": "user_", "type": "address" }], "name": "getUserNFTsOngoingInstallmentPhase", "outputs": [{ "components": [{ "internalType": "bool", "name": "onSale", "type": "bool" }, { "internalType": "address", "name": "sellerAddress", "type": "address" }, { "internalType": "address", "name": "contractAddress", "type": "address" }, { "internalType": "uint8", "name": "installmentsPaid", "type": "uint8" }, { "internalType": "uint8", "name": "paymentsClaimed", "type": "uint8" }, { "internalType": "uint64", "name": "timestamp", "type": "uint64" }, { "internalType": "uint256", "name": "tokenId", "type": "uint256" }, { "internalType": "uint256", "name": "sellingPrice", "type": "uint256" }, { "internalType": "uint256", "name": "totalBids", "type": "uint256" }, { "internalType": "uint256", "name": "selectedBidId", "type": "uint256" }, { "internalType": "enum ProjectY.InstallmentPlan", "name": "installment", "type": "uint8" }], "internalType": "struct ProjectY.SellerInfo[]", "name": "sellerInfos_", "type": "tuple[]" }, { "components": [{ "internalType": "bool", "name": "isSelected", "type": "bool" }, { "internalType": "address", "name": "buyerAddress", "type": "address" }, { "internalType": "uint64", "name": "timestamp", "type": "uint64" }, { "internalType": "uint256", "name": "bidPrice", "type": "uint256" }, { "internalType": "uint256", "name": "entryId", "type": "uint256" }, { "internalType": "uint256", "name": "pricePaid", "type": "uint256" }, { "internalType": "enum ProjectY.InstallmentPlan", "name": "bidInstallment", "type": "uint8" }], "internalType": "struct ProjectY.BuyerInfo[]", "name": "buyerInfos_", "type": "tuple[]" }, { "internalType": "uint256[]", "name": "downPayments_", "type": "uint256[]" }, { "internalType": "uint256[]", "name": "monthlyPayments_", "type": "uint256[]" }, { "internalType": "uint256[]", "name": "entryIds_", "type": "uint256[]" }, { "internalType": "uint256[]", "name": "bidIds_", "type": "uint256[]" }], "stateMutability": "view", "type": "function" }, { "inputs": [{ "internalType": "address", "name": "user_", "type": "address" }], "name": "getUserNFTsOpenForSale", "outputs": [{ "components": [{ "internalType": "bool", "name": "onSale", "type": "bool" }, { "internalType": "address", "name": "sellerAddress", "type": "address" }, { "internalType": "address", "name": "contractAddress", "type": "address" }, { "internalType": "uint8", "name": "installmentsPaid", "type": "uint8" }, { "internalType": "uint8", "name": "paymentsClaimed", "type": "uint8" }, { "internalType": "uint64", "name": "timestamp", "type": "uint64" }, { "internalType": "uint256", "name": "tokenId", "type": "uint256" }, { "internalType": "uint256", "name": "sellingPrice", "type": "uint256" }, { "internalType": "uint256", "name": "totalBids", "type": "uint256" }, { "internalType": "uint256", "name": "selectedBidId", "type": "uint256" }, { "internalType": "enum ProjectY.InstallmentPlan", "name": "installment", "type": "uint8" }], "internalType": "struct ProjectY.SellerInfo[]", "name": "userNFTsOpenForSale_", "type": "tuple[]" }, { "internalType": "uint256[]", "name": "entryIds_", "type": "uint256[]" }], "stateMutability": "view", "type": "function" }, { "inputs": [], "name": "gracePeriod", "outputs": [{ "internalType": "uint64", "name": "", "type": "uint64" }], "stateMutability": "view", "type": "function" }, { "inputs": [{ "internalType": "uint256", "name": "entryId_", "type": "uint256" }], "name": "liquidate", "outputs": [], "stateMutability": "payable", "type": "function" }, { "inputs": [{ "internalType": "address", "name": "", "type": "address" }, { "internalType": "address", "name": "", "type": "address" }, { "internalType": "uint256", "name": "", "type": "uint256" }, { "internalType": "bytes", "name": "", "type": "bytes" }], "name": "onERC721Received", "outputs": [{ "internalType": "bytes4", "name": "", "type": "bytes4" }], "stateMutability": "nonpayable", "type": "function" }, { "inputs": [], "name": "owner", "outputs": [{ "internalType": "address", "name": "", "type": "address" }], "stateMutability": "view", "type": "function" }, { "inputs": [{ "internalType": "uint256", "name": "entryId_", "type": "uint256" }], "name": "payInstallment", "outputs": [], "stateMutability": "payable", "type": "function" }, { "inputs": [{ "internalType": "uint256", "name": "bidId_", "type": "uint256" }], "name": "selectBid", "outputs": [], "stateMutability": "nonpayable", "type": "function" }, { "inputs": [{ "internalType": "address", "name": "contractAddress_", "type": "address" }, { "internalType": "uint256", "name": "tokenId_", "type": "uint256" }, { "internalType": "uint256", "name": "sellingPrice_", "type": "uint256" }, { "internalType": "enum ProjectY.InstallmentPlan", "name": "installment_", "type": "uint8" }], "name": "sell", "outputs": [{ "internalType": "uint256", "name": "", "type": "uint256" }], "stateMutability": "nonpayable", "type": "function" }, { "inputs": [{ "internalType": "uint64", "name": "biddingPeriod_", "type": "uint64" }], "name": "setBiddingPeriod", "outputs": [], "stateMutability": "nonpayable", "type": "function" }, { "inputs": [{ "internalType": "uint64", "name": "gracePeriod_", "type": "uint64" }], "name": "setGracePeriod", "outputs": [], "stateMutability": "nonpayable", "type": "function" }, { "inputs": [{ "internalType": "address", "name": "newOwner", "type": "address" }], "name": "setOwner", "outputs": [], "stateMutability": "nonpayable", "type": "function" }, { "inputs": [{ "internalType": "uint256", "name": "bidId_", "type": "uint256" }], "name": "withdrawBid", "outputs": [], "stateMutability": "nonpayable", "type": "function" }, { "inputs": [{ "internalType": "uint256", "name": "entryId_", "type": "uint256" }], "name": "withdrawPayment", "outputs": [], "stateMutability": "nonpayable", "type": "function" }, { "inputs": [{ "internalType": "uint256", "name": "entryId_", "type": "uint256" }], "name": "withdrawSell", "outputs": [{ "internalType": "uint256", "name": "", "type": "uint256" }], "stateMutability": "nonpayable", "type": "function" }]
export const ERC721ABI = [
  {
    constant: false,
    inputs: [
      { internalType: "address", name: "to", type: "address" },
      { internalType: "uint256", name: "tokenId", type: "uint256" },
    ],
    name: "approve",
    outputs: [],
    payable: false,
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    constant: false,
    inputs: [
      { internalType: "address", name: "to", type: "address" },
      { internalType: "uint256", name: "tokenId", type: "uint256" },
    ],
    name: "mint",
    outputs: [],
    payable: false,
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    constant: false,
    inputs: [
      { internalType: "address", name: "from", type: "address" },
      { internalType: "address", name: "to", type: "address" },
      { internalType: "uint256", name: "tokenId", type: "uint256" },
    ],
    name: "safeTransferFrom",
    outputs: [],
    payable: false,
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    constant: false,
    inputs: [
      { internalType: "address", name: "from", type: "address" },
      { internalType: "address", name: "to", type: "address" },
      { internalType: "uint256", name: "tokenId", type: "uint256" },
      { internalType: "bytes", name: "_data", type: "bytes" },
    ],
    name: "safeTransferFrom",
    outputs: [],
    payable: false,
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    constant: false,
    inputs: [
      { internalType: "address", name: "to", type: "address" },
      { internalType: "bool", name: "approved", type: "bool" },
    ],
    name: "setApprovalForAll",
    outputs: [],
    payable: false,
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    constant: false,
    inputs: [
      { internalType: "address", name: "from", type: "address" },
      { internalType: "address", name: "to", type: "address" },
      { internalType: "uint256", name: "tokenId", type: "uint256" },
    ],
    name: "transferFrom",
    outputs: [],
    payable: false,
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    payable: false,
    stateMutability: "nonpayable",
    type: "constructor",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "address", name: "from", type: "address" },
      { indexed: true, internalType: "address", name: "to", type: "address" },
      {
        indexed: true,
        internalType: "uint256",
        name: "tokenId",
        type: "uint256",
      },
    ],
    name: "Transfer",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "owner",
        type: "address",
      },
      {
        indexed: true,
        internalType: "address",
        name: "approved",
        type: "address",
      },
      {
        indexed: true,
        internalType: "uint256",
        name: "tokenId",
        type: "uint256",
      },
    ],
    name: "Approval",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "owner",
        type: "address",
      },
      {
        indexed: true,
        internalType: "address",
        name: "operator",
        type: "address",
      },
      { indexed: false, internalType: "bool", name: "approved", type: "bool" },
    ],
    name: "ApprovalForAll",
    type: "event",
  },
  {
    constant: true,
    inputs: [{ internalType: "address", name: "owner", type: "address" }],
    name: "balanceOf",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    payable: false,
    stateMutability: "view",
    type: "function",
  },
  {
    constant: true,
    inputs: [{ internalType: "uint256", name: "tokenId", type: "uint256" }],
    name: "getApproved",
    outputs: [{ internalType: "address", name: "", type: "address" }],
    payable: false,
    stateMutability: "view",
    type: "function",
  },
  {
    constant: true,
    inputs: [
      { internalType: "address", name: "owner", type: "address" },
      { internalType: "address", name: "operator", type: "address" },
    ],
    name: "isApprovedForAll",
    outputs: [{ internalType: "bool", name: "", type: "bool" }],
    payable: false,
    stateMutability: "view",
    type: "function",
  },
  {
    constant: true,
    inputs: [{ internalType: "uint256", name: "tokenId", type: "uint256" }],
    name: "ownerOf",
    outputs: [{ internalType: "address", name: "", type: "address" }],
    payable: false,
    stateMutability: "view",
    type: "function",
  },
  {
    constant: true,
    inputs: [{ internalType: "bytes4", name: "interfaceId", type: "bytes4" }],
    name: "supportsInterface",
    outputs: [{ internalType: "bool", name: "", type: "bool" }],
    payable: false,
    stateMutability: "view",
    type: "function",
  },
];
